//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Species()
        {
            this.ResourceLocation = new HashSet<ResourceLocation>();
            this.Tag_Species = new HashSet<Tag_Species>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public long status { get; set; }
        public string icon { get; set; }
        public Nullable<long> IUCN { get; set; }
        public Nullable<long> dth { get; set; }
        public Nullable<long> ppa { get; set; }
        public Nullable<long> ts { get; set; }
        public Nullable<long> ar { get; set; }
        public string dd { get; set; }
        public string type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceLocation> ResourceLocation { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag_Species> Tag_Species { get; set; }
    }
}
