//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_Species
    {
        public long id { get; set; }
        public string sp_id { get; set; }
        public string tag_id { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Species Species { get; set; }
    }
}
